---
title: "STATS506 Problem Set #1"
author: "Bryan Li"
format: html
editor: visual
---

## Problem #1 - Wine Data

### a.

```{r}
wine <- read.table(file = "Datasets/wine/wine.data",
                   sep = ',',
                   col.names = c('class', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'OD280_and_OD314_of_diluted_wines', 'proline'))
head(wine)
```

### b.

```{r}
table(wine$class)
```

wine.names states that there are 59 wines of class 1, 71 of class 2, and 48 of class 3. This is confirmed by the previous table.

### c.

1.  

```{r}
cor(wine$alcohol, wine$color_intensity)
```

2.  

```{r}
cor(wine$alcohol[wine$class == 1], wine$color_intensity[wine$class == 1])
cor(wine$alcohol[wine$class == 2], wine$color_intensity[wine$class == 2])
cor(wine$alcohol[wine$class == 3], wine$color_intensity[wine$class == 3])
```

Class 1 has the highest, class 2 the lowest.

3.  

```{r}
wine$alcohol[wine$color_intensity == max(wine$color_intensity)]
```

4.  

```{r}
proanthocyanins_greater_ash_vec <- c(wine$proanthocyanins > wine$ash)
proanthocyanins_greater_ash_perc <- mean(proanthocyanins_greater_ash_vec)
print(paste("Percentage of Wines with a Higher Content of Proanthocyanins than Ash:", proanthocyanins_greater_ash_perc, sep = ' '))
```

### d.

```{r}
wine_mean_table <- data.frame(Type = c('1', '2', '3', 'Overall'))
for (i in 2:ncol(wine)) {
  class_means <- tapply(wine[, i], wine$class, mean)
  overall_mean <- mean(wine[, i])
  wine_mean_table[names(wine)[i]] <- c(class_means[1], class_means[2], class_means[3], overall_mean)
}
wine_mean_table
```


